# DATABASE_URL=postgresql://postgres:password@localhost:5432/hod_db?schema=public docker compose up -d --build
version: '3.5'

services:
  sc-server:
    build:
      context: .
    container_name: sc_server
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
    restart: always
    networks:
      - sc_network

networks:
  sc_network:
    name: sc_network
