version: '3.8'
services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_service_os
    volumes:
      - /home/fithaui/phoGPT/:/code/
    ports:
      - "8080:80"
    environment:
      - GOOGLE_API_KEY = ${GOOGLE_API_KEY}
    restart: always