name: health-care
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - pip
  - pip:
      - unsloth
      - transformers
      - datasets
      - torch
