name: Deploy Application

on:
  push:
    branches:
      - main
    paths: ['sc-server/**']
  pull_request:
    branches:
      - main
    types: [closed]
    paths: ['sc-server/**']

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server:
              - 'sc-server/**'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to Docker Hub
        if: steps.filter.outputs.server == 'true'
        uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}:sc-server'
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sc_server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sc_server:latest
            docker ps -aq --filter "name=^sc_server$" | xargs -r docker rm -f
            docker run -d \
              --name sc_server \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -p 3000:3000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/sc_server:latest
